### ISSUE TITLE
Internal Synoptic error: ClassCastException

### ISSUE THREAD

**Issue by MJafarMashhadi** [ModelInference/synoptic#420]
```
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
$ uname -a
Darwin MJafars-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
$ ./synoptic.sh thread-8736-io.txt

```

```
Error: java.base/java.util.regex.Matcher$ImmutableMatchResult cannot be cast to java.base/java.util.regex.Matcher
Error traceback:
java.lang.ClassCastException: java.base/java.util.regex.Matcher$ImmutableMatchResult cannot be cast to java.base/java.util.regex.Matcher
	at synoptic.util.matching.NamedMatcher.<init>(NamedMatcher.java:22)
	at synoptic.util.matching.NamedMatcher.toMatchResult(NamedMatcher.java:59)
	at synoptic.main.parser.TraceParser.parseLine(TraceParser.java:908)
	at synoptic.main.parser.TraceParser.parseTrace(TraceParser.java:697)
	at synoptic.main.parser.TraceParser.parseTraceFile(TraceParser.java:607)
	at synoptic.main.AbstractMain.parseEvents(AbstractMain.java:438)
	at synoptic.main.AbstractMain.parseIntoTraceGraph(AbstractMain.java:697)
	at synoptic.main.AbstractMain.createInitialPartitionGraph(AbstractMain.java:544)
	at synoptic.main.SynopticMain.main(SynopticMain.java:47)

	at synoptic.util.InternalSynopticException.wrap(InternalSynopticException.java:88)
	at synoptic.main.SynopticMain.main(SynopticMain.java:54)

```

**Comment by ohmann** [comment]
My first guess would be that it's a Java 10 issue. I think the latest Java version I personally have run Synoptic under is 8. By chance do you also have any earlier JRE versions installed?

**Comment by MJafarMashhadi** [comment]
That was my first guess, so I checked the ant build files and realized that the compiler is targeted to Java 7 (https://github.com/ModelInference/synoptic/blob/master/synoptic/build.xml#L48).

I don't have other java versions installed right now, do you think that if I install an older version of JRE, say 8, the error will be gone?

**Comment by donghwan-shin** [comment]
The same issue here. I resolve this issue by switching Java8 from Java11. It solved for me.

**Comment by tuotuoZ** [comment]
Same here, I switched to Java8 from Java14. Should this be mentioned in the setup tutorial?

**Comment by zaporter** [comment]
Any updates on this? I seem to still have these problems even on Java 11.0.17. Did you end up having to modify the build.xml files? I updated the target and src to 11 but am having no luck. I get the error that:

`Error: class java.util.regex.Matcher$ImmutableMatchResult cannot be cast to class java.util.regex.Matcher (java.util.regex.Matcher$ImmutableMatchResult and java.util.regex.Matcher are in module java.base of loader 'bootstrap')`
